version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - r-base-core
    - r-base-dev
    - libtirpc-dev  # https://bugs.launchpad.net/ubuntu/+source/r-base/+bug/2120296
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
