version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - asdf plugin-add r https://github.com/asdf-community/asdf-r.git
      - asdf install r 4.3.1
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
