version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - r-base-core
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
